//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Upup.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Upup.Globalization.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm sản phẩm vào giỏ hàng thành công.
        /// </summary>
        public static string Add_Cart_Success {
            get {
                return ResourceManager.GetString("Add_Cart_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm số điện thoại thành công.
        /// </summary>
        public static string AddPhoneSuccess {
            get {
                return ResourceManager.GetString("AddPhoneSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu của bạn đã được đổi.
        /// </summary>
        public static string ChangePasswordSuccess {
            get {
                return ResourceManager.GetString("ChangePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui xác thực email của bạn bằng cách click vào link dưới đây: &lt;a href=&quot;{0}&quot;&gt;Xác thực&lt;/a&gt;.
        /// </summary>
        public static string Confirm_email_body {
            get {
                return ResourceManager.GetString("Confirm_email_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác thực tài khoản email tại Upup.
        /// </summary>
        public static string Confirm_email_title {
            get {
                return ResourceManager.GetString("Confirm_email_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận mật khẩu mới.
        /// </summary>
        public static string Confirm_New_Password {
            get {
                return ResourceManager.GetString("Confirm_New_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu hiện tại.
        /// </summary>
        public static string Current_Password {
            get {
                return ResourceManager.GetString("Current_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra, xin vui lòng thử lại.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code không chính xác.
        /// </summary>
        public static string Invalid_Code {
            get {
                return ResourceManager.GetString("Invalid_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản hoặc mật khẩu không chính xác.
        /// </summary>
        public static string Invalid_Login {
            get {
                return ResourceManager.GetString("Invalid_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi nhớ tài khoản.
        /// </summary>
        public static string Login_Remember_Me {
            get {
                return ResourceManager.GetString("Login_Remember_Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới.
        /// </summary>
        public static string New_Password {
            get {
                return ResourceManager.GetString("New_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng đã được đặt thành công, chúng tôi sẽ liên lạc với bạn ngay khi có thể.
        /// </summary>
        public static string Order_Success {
            get {
                return ResourceManager.GetString("Order_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã đặt hàng.
        /// </summary>
        public static string Ordered {
            get {
                return ResourceManager.GetString("Ordered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khác.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu và mật khẩu xác nhận không khớp.
        /// </summary>
        public static string Password_Does_Not_Match {
            get {
                return ResourceManager.GetString("Password_Does_Not_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm không tồn tại.
        /// </summary>
        public static string Product_not_exists {
            get {
                return ResourceManager.GetString("Product_not_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ 1.
        /// </summary>
        public static string Register_Address1 {
            get {
                return ResourceManager.GetString("Register_Address1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ 2.
        /// </summary>
        public static string Register_Address2 {
            get {
                return ResourceManager.GetString("Register_Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ 3.
        /// </summary>
        public static string Register_Address3 {
            get {
                return ResourceManager.GetString("Register_Address3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ 4.
        /// </summary>
        public static string Register_Address4 {
            get {
                return ResourceManager.GetString("Register_Address4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hàng không/Quốc phòng.
        /// </summary>
        public static string Register_Aerospace_Defense {
            get {
                return ResourceManager.GetString("Register_Aerospace_Defense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tự động hóa.
        /// </summary>
        public static string Register_Automation {
            get {
                return ResourceManager.GetString("Register_Automation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ô tô.
        /// </summary>
        public static string Register_Automotive {
            get {
                return ResourceManager.GetString("Register_Automotive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công ty thương mại.
        /// </summary>
        public static string Register_CommerceCompany {
            get {
                return ResourceManager.GetString("Register_CommerceCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên công ty hoặc tổ chức.
        /// </summary>
        public static string Register_Company_Name {
            get {
                return ResourceManager.GetString("Register_Company_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản xuất linh kiện.
        /// </summary>
        public static string Register_ComponentManufacturing {
            get {
                return ResourceManager.GetString("Register_ComponentManufacturing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bộ phận.
        /// </summary>
        public static string Register_Department {
            get {
                return ResourceManager.GetString("Register_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổ chức giáo dục.
        /// </summary>
        public static string Register_EducationOrganization {
            get {
                return ResourceManager.GetString("Register_EducationOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện tử.
        /// </summary>
        public static string Register_Electronics {
            get {
                return ResourceManager.GetString("Register_Electronics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Register_Email {
            get {
                return ResourceManager.GetString("Register_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email(Xác nhận).
        /// </summary>
        public static string Register_Email_Confirm {
            get {
                return ResourceManager.GetString("Register_Email_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email đã tồn tại.
        /// </summary>
        public static string Register_Email_Existed {
            get {
                return ResourceManager.GetString("Register_Email_Existed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hội chợ/Hội thảo.
        /// </summary>
        public static string Register_Exhibition_Seminar {
            get {
                return ResourceManager.GetString("Register_Exhibition_Seminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Register_Fax {
            get {
                return ResourceManager.GetString("Register_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thực phẩm/Tiêu dùng.
        /// </summary>
        public static string Register_Food_Consumable {
            get {
                return ResourceManager.GetString("Register_Food_Consumable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổ chức chính phủ.
        /// </summary>
        public static string Register_GovernmentOrganization {
            get {
                return ResourceManager.GetString("Register_GovernmentOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiết bị ổ cứng.
        /// </summary>
        public static string Register_Hard_Disk_Drive {
            get {
                return ResourceManager.GetString("Register_Hard_Disk_Drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet.
        /// </summary>
        public static string Register_Internet {
            get {
                return ResourceManager.GetString("Register_Internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn biết chúng tôi từ đâu.
        /// </summary>
        public static string Register_Know_Us_From {
            get {
                return ResourceManager.GetString("Register_Know_Us_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Màn hình tinh thể lỏng.
        /// </summary>
        public static string Register_Liquid_Crystal_Display {
            get {
                return ResourceManager.GetString("Register_Liquid_Crystal_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chế tạo máy.
        /// </summary>
        public static string Register_MachineManufacturing {
            get {
                return ResourceManager.GetString("Register_MachineManufacturing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xưởng gia công.
        /// </summary>
        public static string Register_MachiningWorkshop {
            get {
                return ResourceManager.GetString("Register_MachiningWorkshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạp chí/Quảng cáo.
        /// </summary>
        public static string Register_Magazine_Trade_Publication {
            get {
                return ResourceManager.GetString("Register_Magazine_Trade_Publication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngành nghề phục vụ chính.
        /// </summary>
        public static string Register_Main_Served_Industry {
            get {
                return ResourceManager.GetString("Register_Main_Served_Industry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thực phẩm/Tiêu dùng.
        /// </summary>
        public static string Register_Medical {
            get {
                return ResourceManager.GetString("Register_Medical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        public static string Register_Name {
            get {
                return ResourceManager.GetString("Register_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số nhân viên thiết kế.
        /// </summary>
        public static string Register_Number_Of_Designer {
            get {
                return ResourceManager.GetString("Register_Number_Of_Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng số nhân viên.
        /// </summary>
        public static string Register_Number_Of_Employee {
            get {
                return ResourceManager.GetString("Register_Number_Of_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string Register_Password {
            get {
                return ResourceManager.GetString("Register_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu (Xác nhận).
        /// </summary>
        public static string Register_Password_Confirm {
            get {
                return ResourceManager.GetString("Register_Password_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại.
        /// </summary>
        public static string Register_Phone {
            get {
                return ResourceManager.GetString("Register_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã bưu điện.
        /// </summary>
        public static string Register_Postal_Code {
            get {
                return ResourceManager.GetString("Register_Postal_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quảng bá.
        /// </summary>
        public static string Register_Publicity {
            get {
                return ResourceManager.GetString("Register_Publicity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Được giới thiệu (đồng nghiệp).
        /// </summary>
        public static string Register_Referrel_Colleagues {
            get {
                return ResourceManager.GetString("Register_Referrel_Colleagues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Được giới thiệu (Khách hàng/Đối tác).
        /// </summary>
        public static string Register_Referrel_Customers_Business_Partners {
            get {
                return ResourceManager.GetString("Register_Referrel_Customers_Business_Partners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin đăng nhập.
        /// </summary>
        public static string Register_Section_Login_Info {
            get {
                return ResourceManager.GetString("Register_Section_Login_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng câu hỏi.
        /// </summary>
        public static string Register_Section_Questionnaire {
            get {
                return ResourceManager.GetString("Register_Section_Questionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin người dùng.
        /// </summary>
        public static string Register_Section_User_Info {
            get {
                return ResourceManager.GetString("Register_Section_User_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Hãy chọn --.
        /// </summary>
        public static string Register_Select {
            get {
                return ResourceManager.GetString("Register_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bán dẫn.
        /// </summary>
        public static string Register_Semiconductor {
            get {
                return ResourceManager.GetString("Register_Semiconductor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký thành công.
        /// </summary>
        public static string Register_Success {
            get {
                return ResourceManager.GetString("Register_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngành nghề kinh doanh.
        /// </summary>
        public static string Register_Type_of_Business {
            get {
                return ResourceManager.GetString("Register_Type_of_Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID đăng nhập.
        /// </summary>
        public static string Register_UserId {
            get {
                return ResourceManager.GetString("Register_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id đăng nhập đã tồn tại.
        /// </summary>
        public static string Register_UserName_Existed {
            get {
                return ResourceManager.GetString("Register_UserName_Existed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúng tôi đã gửi tới bạn một email chứa liên kết dùng để xác thực email, vui lòng kiểm tra hộp thư để kích hoạt tài khoản của bạn.
        /// </summary>
        public static string Register_Verify_Email {
            get {
                return ResourceManager.GetString("Register_Verify_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi nhớ.
        /// </summary>
        public static string Remember_Me {
            get {
                return ResourceManager.GetString("Remember_Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thành công.
        /// </summary>
        public static string Remove_success {
            get {
                return ResourceManager.GetString("Remove_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa số điện thoại thành công.
        /// </summary>
        public static string RemovePhoneSuccess {
            get {
                return ResourceManager.GetString("RemovePhoneSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhấn vào liên kết dưới đây để đặt lại mật khẩu của bạn: &lt;a href=&quot;{0}&quot;&gt;Đặt lại mật khẩu&lt;/a&gt;.
        /// </summary>
        public static string Reset_password_body {
            get {
                return ResourceManager.GetString("Reset_password_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt lại mật khẩu Upup.
        /// </summary>
        public static string Reset_password_title {
            get {
                return ResourceManager.GetString("Reset_password_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu đã được đặt thành công.
        /// </summary>
        public static string SetPasswordSuccess {
            get {
                return ResourceManager.GetString("SetPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt xác thực hai bước thành công.
        /// </summary>
        public static string SetTwoFactorSuccess {
            get {
                return ResourceManager.GetString("SetTwoFactorSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy user.
        /// </summary>
        public static string User_Not_Found {
            get {
                return ResourceManager.GetString("User_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sai mật khẩu.
        /// </summary>
        public static string Wrong_Password {
            get {
                return ResourceManager.GetString("Wrong_Password", resourceCulture);
            }
        }
    }
}
