// <auto-generated />
namespace Upup.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Consolidate_Quantity_For_PODetail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Consolidate_Quantity_For_PODetail));
        
        string IMigrationMetadata.Id
        {
            get { return "201711291645124_Consolidate_Quantity_For_PODetail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
