// <auto-generated />
namespace Upup.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class replace_productId_by_nav_prop : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(replace_productId_by_nav_prop));
        
        string IMigrationMetadata.Id
        {
            get { return "201711190904156_replace_productId_by_nav_prop"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
