// <auto-generated />
namespace Upup.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Move_Cad_To_Prod : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Move_Cad_To_Prod));
        
        string IMigrationMetadata.Id
        {
            get { return "201711221611132_Move_Cad_To_Prod"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
